title: "AlexBot Public"
description: "AI Security Challenge, Learning Guides & Public Resources"
baseurl: ""
url: "https://www.alextwin.ai"
plugins:
  - jekyll-seo-tag
exclude:
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
